add code
dark0ghost/tech-C-task2 pull request #1
Opened 2021-03-26 20:22 UTC by dark0ghost

2021-03-30 19:36 UTC, leshiy1295 requested changes

2021-03-30 19:36 UTC, leshiy1295 commented on .github/workflows/greetings.yml
> +
https://github.com/dark0ghost/tech-C-task2/pull/1/checks#step:9:114

2021-03-30 19:36 UTC, leshiy1295 commented on .github/workflows/greetings.yml
> +
ссылка на CodeCov возвращает 404 :(

2021-03-30 19:36 UTC, leshiy1295 commented on .github/workflows/greetings.yml
> +
и сейчас CI запускается две сборки - на PR и ветку. Должна только одна

2021-03-30 19:36 UTC, leshiy1295 commented on CMakeLists.txt
> +#set(THREADS_PREFER_PTHREAD_FLAG TRUE)
комментариев с нерабочим кодом быть не должно

2021-03-30 19:36 UTC, leshiy1295 commented on CMakeLists.txt
> +add_library(${PROJECT_NAME}_lib STATIC src/c/task2/one_thread/one_thread.h src/c/task2/one_thread/one_thread.c)
название файлов не должно отражать суть имплементации. Header-файл должен быть общим для обеих реализаций

2021-03-30 19:36 UTC, leshiy1295 commented on CMakeLists.txt
> +target_link_libraries(stress_test  ${PROJECT_NAME}_lib ${PROJECT_NAME}_dynamic_lib GTest::GTest GTest::Main)
возможность одновременного подключения обеих библиотек сигнализирует о том, что Вы не выполнили одно из требований ИЗ, согласно которому обе библиотеки должны использовать единый интерфейс

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/main.c
> +    input_data(scanf, printf);
что это?
и почему input принимает printf?
зачем main вообще передаёт знание о реализации??? Он может передать stdin/stdout, а то, как оно реализовано внутри, main интересовать не должно

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/input_data.c
> +#include "multi_thread/thread_data.h"
в алфавитном порядке

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/input_data.c
> +    unsigned long number = 2;
магических констант быть не должно

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/input_data.c
> +    auto core = sysconf(_SC_NPROCESSORS_ONLN);
auto в Си - не то же самое, что auto в C++.

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/input_data.c
> +    one_thread(&data, test_func, &main_struct);
функции должны называться глаголами

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/input_data.c
> +    out("multi thread %f", data.diff_time);
функция input не должна вызывать функцию обработки, она должна вводить данные

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/input_data.c
> +    thread_start(&data, test_func, &number);
клиент не должен знать, какая реализация используется, он должен всегда вызывать одну интерфейсную функцию

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/lib/func_prototype.h
> +typedef void* (func_test) (void* vargp);
совершенно непонятны название файла и назначение функции

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/lib/main_struct.h
> +struct Data{
непонятное название структуры, непонятное назначение полей, почему используется long вместо int - тоже неясно

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/lib/main_struct.h
> +    unsigned long size;
size_t

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.c
> +extern void* thread_start(struct Data* st, func_test func,  void* arg){
функции по умолчанию имеют внешнее связывание...

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.c
> +    pthread_t* tid = (pthread_t*)calloc(st->total, sizeof(pthread_t));
calloc может вернуть ошибку

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.c
> +        if(pthread_create(&tid[i], NULL, func, arg)!= 0)
во-первых, скобки {}
во-вторых, если 10 потоков создастся, а 11-й - нет, то сейчас первые 10 потоков останутся зомби

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.c
> +    time_t end = time(NULL);
в многопоточных программах time работает не так, как ожидается... Об этом в условии задания написано

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.c
> +    time_t end = time(NULL);
измерять время выполнения функции внутри функции - некорректно

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.c
> +    time_t end = time(NULL);
измерять время однократного выполнения - некорректно

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/multi_thread/thread_data.h
> +#include "../lib/main_struct.h"
относительный include - недоработка в CMake

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/test_func/test_func.c
> +        test_array[i + 2] = '2';
во-первых, есть ещё и '3' по условию, во-вторых, это не должно быть хардкодом, инициализация может быть любой, "логика" инициализации должна передаваться извне

2021-03-30 19:36 UTC, leshiy1295 commented on src/c/task2/test_func/test_func.c
> +        exit(-1);
добрый вечер :)
так совсем плохо делать

2021-03-30 19:36 UTC, leshiy1295 commented on src/test/stress_test.cpp
> +TEST(stress_test, tests_input) {
стресс-тест отсутствует

2021-03-30 19:36 UTC, leshiy1295 commented on src/test/test.cpp
> +
это не юнит-тесты, это интеграционные тесты, которые ещё и непонятно что тестируют. Это говорит о том, что сама программа, сам её интерфейс, спроектированы плохо

2021-03-30 19:48 UTC, dark0ghost commented on .github/workflows/greetings.yml
> +
> ссылка на CodeCov возвращает 404 :(

https://codecov.io/gh/dark0ghost/tech-C-task2/commit/8098b8300414fa17ef166da4f0734116f6726a27/graphs

2021-03-30 20:25 UTC, dark0ghost commented on src/c/task2/lib/main_struct.h
> +struct Data{
> непонятное название структуры, непонятное назначение полей, почему используется long вместо int - тоже неясно

`/* Get the value of the system variable NAME.  */
extern long int sysconf (int __name) __THROW;`

2021-03-30 21:05 UTC, dark0ghost commented on CMakeLists.txt
> +target_link_libraries(stress_test  ${PROJECT_NAME}_lib ${PROJECT_NAME}_dynamic_lib GTest::GTest GTest::Main)
мне нужно сделать интерфейс поверх этих?

2021-05-13 17:55 UTC, dark0ghost commented
Update ИЗ2

2021-05-23 14:43 UTC, leshiy1295 reviewed
Отсутствует формулировка задачи.
Остальные замечания - в комментариях. К сожалению, код довольно слабый и использует много хардкода.

2021-05-23 14:43 UTC, leshiy1295 commented on .github/workflows/test.yml
> +on:  [pull_request, push]
зачем делать две сборки?

2021-05-23 14:43 UTC, leshiy1295 commented on .github/workflows/test.yml
> +
сейчас superlinter выдаёт ошибки

2021-05-23 14:43 UTC, leshiy1295 commented on .github/workflows/test.yml
> +  # Configuration type to build.
в отчётах по coverage зачем-то присутствует gtest

2021-05-23 14:43 UTC, leshiy1295 commented on .github/workflows/test.yml
> +  # Configuration type to build.
есть ещё файлы тестов, но сами файлы просмотреть нельзя из-за 404

2021-05-23 14:43 UTC, leshiy1295 commented on .github/workflows/test.yml
> +  # Configuration type to build.
файлов с кодом решения задачи в отчётах нет

2021-05-23 14:43 UTC, leshiy1295 commented on CMakeLists.txt
> +add_executable(stress_test_dynamic src/test/stress_test_dynamic.cpp src/c/task2/test_func/test_func.h src/c/task2/test_func/test_func.c)
собираться должна только одна библиотека в зависимости от выбора пользователя

2021-05-23 14:43 UTC, leshiy1295 commented on .github/workflows/test.yml
> +        run: cd .. && bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}}
отсутствует valgrind

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/hard_init/hard_init.c
> +    }
хардкод.. Если потребуется заполнять другим паттерном - придётся все переписывать

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/lib/main_struct.h
> +#pragma pack(push, 1)
зачем?

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/lib/multi_thread/start_task.c
> +    for(long i = 0; i < arg->total; i++) {
зачем используется long вместо Int?

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/lib/multi_thread/start_task.c
> +#include "../main_struct.h"
относительный путь - недоработка в CMake

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/lib/multi_thread/start_task.c
> +            return NULL;
return из цикла - плохо

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/lib/multi_thread/start_task.c
> +                pthread_join(tid[i], NULL);
если упало на 2 из 1000, то Вы зачем-то будете и все остальные пытаться заджойнить...

2021-05-23 14:43 UTC, leshiy1295 commented on src/c/task2/test_func/test_func.c
> +    if (arg == NULL)
никогда не экономьте на {}

2021-05-23 14:43 UTC, leshiy1295 commented on src/test/stress_test_dynamic.cpp
> +    std::cout << sum_diff.count() / 100 << std::endl;
число 100 захардкожено три раза

2021-05-23 14:43 UTC, leshiy1295 commented on src/test/stress_test_static.cpp
> +        time_t start = time(nullptr);
почему интерфейс для замера времени разный? Сделали бы общую подпрограмму за измерения времени

2021-05-23 14:43 UTC, leshiy1295 commented on src/test/stress_test_static.cpp
> +
отсутствуют тесты на саму реализацию

2021-06-19 19:25 UTC, closed without merging